### ISSUE TITLE
private method `browser_name' called for {:browserName=>:firefox, :version=>nil}:Hash (NoMethodError)

### ISSUE THREAD

**Issue by mlotfi2005** [continuousqa/seleniumServerSetup#1]
HI,
I am following your tutorial 
http://sdet.us/selenium-server-grid-with-watir-cucumber/

but when I tried to run cucumber for one of your features , I got 

cucumber features\amazon_search.feature
C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:135:in `require': `require "watir-webdriver"` is deprecated. Please, use `require "watir"`.
Deprecated: Found tagged hook with '@Ex_tag1, @Ex_tag2'. Support for '@tag1,@tag2' will be removed from the next release of Cucumber. Please use '@tag or @tag2' instead.
Deprecated: Found tagged hook with '@Ex_tag1, @Ex_tag2'. Support for '@tag1,@tag2' will be removed from the next release of Cucumber. Please use '@tag or @tag2' instead.
Feature: Searching on Amazon

  Scenario: Testing Search                             # features/amazon_search.feature:2
  private method `browser_name' called for {:browserName=>:firefox, :version=>nil}:Hash (NoMethodError)
  ./features/support/env.rb:39:in `new'
  ./features/support/env.rb:39:in `Before'
    Given a user is at amazon                          # features/step_definitions/my_steps.rb:1
    When they enter some key value in the search box   # features/step_definitions/my_steps.rb:5
    Then the propper results will appear on the screen # features/amazon_search.feature:5
      undefined method `close' for nil:NilClass (NoMethodError)
      ./features/support/env.rb:49:in `After'

Failing Scenarios:
cucumber features/amazon_search.feature:2 # Scenario: Testing Search

1 scenario (1 failed)
3 steps (2 skipped, 1 undefined)
0m0.185s

THanks, your help is appreciated.

**Comment by continuousqa** [comment]
Hi there,

so the answer to your question is within the error output.  You will find in development and QA, open source frameworks (like Watir) will change periodically.  I suppose I should make a new tutorial, but I just don’t have the time.  In any case, I’ll explain what’s going on.

At one time the Watir project was broken into two projects:
 - Watir
 - Watir-Webdriver

Watir was a rudimentary start of web/browser automation, and it was fully compatible with Internet Explorer (which in itself was a feat.) 

Watir-webdriver was more robust and worked with a variety of browsers (Chrome, IE, Firefox and with a little help - Safari.)

Over the years, many changes have come into play… such as Firefox’s new core technology (Marianette) which broke Watir with modern FF versions from running.  

At any rate, it appears that the latest version of Watir and Watir-Webdriver have code that now makes using watir-webdriver defunct.  

When I see something like this, the first thing to do is grab the core output message in the error and google “watir-webdriver deprecated.”  Which brings me to Watir’s github repo and sure enough, they no longer support Watir-Webdriver. You will now need to do your automation in Watir instead.  

If you check out Watir.com you will see some examples of using Watir to run a variety of browsers.  This is where you’ll want to pull from.  Watir is very simple and the syntax is probably very similar.  

So for you… you would remove the require watir-webdriver and replace it with just watir.  you will also need to review your code.

What I’d recommend is you start simple: Create a new project, just make a simple ruby file (no cucumber, nothing else) and have that file require the watir library.  If you like you can use a .Gemfile to source watir and then pull it down from the command line (or install it by hand), just like you did with watir-webdriver.

Ok… once you have it setup, in one simple .rb file just do a b = Watir::Browser.new :chrome and then 
b.goto(“http://google.com”) 

you should be able to run this file in the IDE or from the command line using: ruby [yourfilename].rb  

That should launch Chrome and go to google.com  

Once you are familiarized with this simple test… you know you have it all working, then go back to the original tutorial and try and use the same code.  Keep in mind that the tags I tried to hook to in my examples, existed when I wrote the tutorial several years ago.  Google and Amazon may have changed their HTML identifiers and class values.  so you may have to do some work to figure out the right tags to hook to.

**Comment by mlotfi2005** [comment]
Thanks, lot, I appreciate your long explanation,
